### ISSUE TITLE
How to add an action

### ISSUE THREAD

**Issue by ravibishnoi** [Syngmaster/BadgedBarButtonItem#1]
Can you please explain how to add an action to this UIBarButton Item. it looks fine but I am having an issue with this button action (I want to sent a selector and on this click I want to open a new screen).

**Comment by justdan0227** [comment]
You sould be able to do it with:

 let barBtn = BadgedButtonItem(with: UIImage(systemName: "person.fill.badge.plus"))
 barBtn.tapAction = {
     
   present(YOURVIEWCONTROLLER, animated: true)

    }
